name: check_update
description: "Flutter package to check for app updates"
version: 0.0.3
homepage: https://github.com/mohammedjaf96/check_update.git
repository: https://github.com/mohammedjaf96/check_update.git

environment:
  sdk: ^3.7.0
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter
  package_info_plus:
  http:

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:


